### ISSUE TITLE
大佬你这个咋用啊

### ISSUE THREAD

**Issue by Audi-dask** [happysooner/WechatWorkRobot#1]
大佬你这个咋用啊，看了半天源码没看明白咋使用

**Comment by unliar** [comment]
> 大佬你这个咋用啊，看了半天源码没看明白咋使用

啊这 就 https://github.com/happysooner/WechatWorkRobot/blob/master/robot_test.go 里面的测试代码

```
// 实例化一个机器人
var robot = Robot{Key: 你的机器人key}

// 调用方法
robot.sendXXX
